### ISSUE TITLE
Generation of correspondence matching between two images script

### ISSUE THREAD

**Issue by touranisatyajit** [oravus/lostX#1]
Hi, 

Could you please generate the script of how to find the correspondences between the two matching images using the found descriptors? Not exactly sure on how to do that using the given format of the descriptors? Or atleast could you provide a brief method on how you did it? 

Thanks.

**Comment by oravus** [comment]
Although late, for those looking into this in future, please refer to [this part of the code](https://github.com/oravus/lostX/blob/a26560d8e14bb1fc9a2ff6ade4cbaa9cf1a52006/lost_kc/match_lost_kc.py#L89) to obtain keypoint correspondences.
