### ISSUE TITLE
pretrained model on SYNTHIA dataset

### ISSUE THREAD

**Issue by BYQ-ZJU** [oravus/lostX#2]
would you please upload trained model on SYNTHIA?

**Comment by oravus** [comment]
Hi, we used RefineNet trained on the Cityscapes dataset for semantic segmentation. The trained models for that can be downloaded by visiting https://github.com/guosheng/refinenet

**Comment by BYQ-ZJU** [comment]
> Hi, we used RefineNet trained on the Cityscapes dataset for semantic segmentation. The trained models for that can be downloaded by visiting https://github.com/guosheng/refinenet
thank you for the reply.
