### ISSUE TITLE
Sequence Matching with LoST-X

### ISSUE THREAD

**Issue by specarmi** [oravus/lostX#3]
Hello,

I'm hoping to implement sequence matching with LoST-X as presented in the paper, but I don't fully understand this statement in the paper:

> We use a slight variant of the publicly available OpenSeqSLAM [26] with an induced ability to accumulate sequence scores for only the top matching candidates generated using the LoSTX framework

Can you clarify how this is performed or share the modification of OpenSeqSLAM that was used?

Thank you!

**Comment by oravus** [comment]
Hi @specarmi, we update the distance matrix as follows before running sequence matching: 

```
dMat[rIdx,qIdx] *= d
```

where `dMat` is the distance matrix computed using global descriptors (LoST), `rIdx` is one of the top N (=10) candidate indices for a given query idx `qIdx` and `d` is the distance obtained from keypoint matching for the candidate pair (as [here](https://github.com/oravus/lostX/blob/a26560d8e14bb1fc9a2ff6ade4cbaa9cf1a52006/lost_kc/match_lost_kc.py#L96)).

Hope that helps!

**Comment by specarmi** [comment]
Hello @oravus, just to confirm: is the value of `d` here set directly from the line you referenced
https://github.com/oravus/lostX/blob/a26560d8e14bb1fc9a2ff6ade4cbaa9cf1a52006/lost_kc/match_lost_kc.py#L96
or the line just after it where the value from the previous line is normalized by the number of semantically consistent correspondences
https://github.com/oravus/lostX/blob/a26560d8e14bb1fc9a2ff6ade4cbaa9cf1a52006/lost_kc/match_lost_kc.py#L100

The next line implies it is the latter:
https://github.com/oravus/lostX/blob/a26560d8e14bb1fc9a2ff6ade4cbaa9cf1a52006/lost_kc/match_lost_kc.py#L102

Thank you for your help!

**Comment by oravus** [comment]
Yep, the latter actually. The value being appended in L102 is the same as the equation I put in my previous comment.
